server:
  port: 8090

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/quizdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 15
    registry-fetch-interval-seconds: 5

resilience4j:
  circuitbreaker:
    instances:
      questionService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
